on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n conregnamedaan -g conregnamedaan818f-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n conregnamedaan --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n conregnamedaan --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n conregnamedaan --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: conregnamedaan.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t conregnamedaan.azurecr.io/k8clusterdtoes:${{ github.sha }}
        docker push conregnamedaan.azurecr.io/k8clusterdtoes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_k8clusterdtoes_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8cluster-dtoes8602 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8cluster-dtoes8602`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8cluster-dtoes8602
        container-registry-url: conregnamedaan.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: k8clusterdtodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8cluster-dtoes8602
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          conregnamedaan.azurecr.io/k8clusterdtoes:${{ github.sha }}
        imagepullsecrets: |
          k8clusterdtodockerauth